### ISSUE TITLE
missing login credentials for ubuntu-mate-x2go-desktop image

### ISSUE THREAD

**Issue by zocker-160** [Floppe/docker#1]
I've set up a ubuntu-mate-x2go-desktop container and I am able to connect to it, but what is the password of the root user?

optimal would be, if you could set it in a ENV variable

**Comment by Floppe** [comment]
I haven't used that container for a long time, but there are environments variables to override password generator.

As default, the password is scrambled and logged so one can get it from the logs.

ROOT_PASS can be used to set own password instead of using auto generated one.
USER should be used to create a ordinary username. Remember to use lower case.
USER_PASS , same idea as ROOT_PASS
